### ISSUE TITLE
pipeline not found?

### ISSUE THREAD

**Issue by silvacarl2** [mystic-ai/pipeline#303]
did this:

pip install -U pipeline-ai

then this:

`pipeline cluster login catalyst-api token -u https://mystic.ai`

causes this: 

pipeline command not found

**Comment by paulcjh** [comment]
Hi @silvacarl2 just removed your public token there, I recommend deleting it as well on the dashboard as it has been exposed.

Which operating system are you on? The above would suggest that you have a venv issue on your system

**Comment by silvacarl2** [comment]
thx done.
