### ISSUE TITLE
Default values of bool pipeline arguments are turning to strings 

### ISSUE THREAD

**Issue by the-crypt-keeper** [mystic-ai/pipeline#382]
Observe the parameter values for this default run (nothing changed, I just loaded the page and but Run):

 https://www.mystic.ai/mikesai/mistral-7b-instruct-v0.2-awq:v1/my-runs/run_9fa8cd570cf74633bb44cd3e37d55f84

There are 3 booleans here:

```
    use_beam_search: bool | None = InputField(default=False)
    full_result: bool | None = InputField(default=False)
    ignore_eos: bool | None = InputField(default=False)
```

Notice the default value of "false" (str) instead of False (bool) in the call:

```
"use_beam_search": "false",
...
"full_result": "false",
"ignore_eos": "false",
```

This type mismatch causes my pipeline misbehavior.

Known Workaround: for each boolean option, turn it off and on again before clicking Run.

**Comment by plutopulp** [comment]
Hi @the-crypt-keeper, thanks for flagging the issue! It was an issue with how boolean inputs were being set in the form on the frontend. We'll be redeploying a fix for this shortly.
