### ISSUE TITLE
pipeline: command not found

### ISSUE THREAD

**Issue by mingdianliu** [mystic-ai/pipeline#449]
I met with pipeline: command not found though I have installed pipeline-ai. Could you please help me with this issue? Thank you.

**Comment by mingdianliu** [comment]
I resolved the last issue since I installed pipeline-api in Anaconda environment. 

I have one more issue here. Could you please have a look at this issue?

$ pipeline cluster login mystic-api MY_TOKEN -u https://www.mystic.ai -a
Pipeline 17:58:17 - [ERROR]: Couldn't authenticate with https://www.mystic.ai

**Comment by ibaraki-douji** [comment]
did you replaced the `MY_TOKEN` with your API token ?? and is it the right one ??

**Comment by paulcjh** [comment]
Hey @mingdianliu did you manage to fix this? As @ibaraki-douji I think it's to do with the replacing of `MY_TOKEN`

**Comment by mingdianliu** [comment]
I have solved this issue. 

I believe the commands on Dashboard Overview and Document Quickstart are different from each other. Please check their differences:

Dashboard Overview:
`pipeline cluster login -u https://www.mystic.ai -a mystic-api API_TOKEN`

Document Quickstart:
`pipeline cluster login mystic-api API_TOKEN -u https://www.mystic.ai -a`
