### ISSUE TITLE
Pydantic v2 conflict with latest VLLM

### ISSUE THREAD

**Issue by ilyalasy** [mystic-ai/pipeline#482]
Hi, having latest versions of pipeline-ai and vllm:
```
requirements:
      - pipeline-ai==2.6.2
      - vllm==0.5.4
```
results in dependency conflict over pydantic:
```
Pipeline 14:40:59 - [INFO]: The conflict is caused by:
    pipeline-ai 2.6.2 depends on pydantic<2.0.0 and >=1.8.2
    vllm 0.5.4 depends on pydantic>=2.0
```
Is there any plans to update pydantic dependency to v2?

**Comment by McFredward** [comment]
I've submitted a pull request from my fork that resolves the issue (https://github.com/mystic-ai/pipeline/pull/487). 
In the meantime, you can use my fork here: https://github.com/McFredward/mystic
