### ISSUE TITLE
Pipeline Cloud does not enable new project creation or deployment

### ISSUE THREAD

**Issue by plutopulp** [mystic-ai/pipeline#89]
it would be nice to be able to create (or get a list) of projects on user account and with the project ID be able to call a
`api.deploy(pipeline_id, project_id)` that returns the `pipeline_id` which in turn we could use to execute runs in the new project all with the python client.

**Comment by alexpearce** [comment]
In general it would be nice if the library acted as a more general API client, e.g.

```python
project = api.Project.create(name="…")
deployment = api.Deployment(project=project, pipeline="pipeline_abc123")
```
